### ISSUE TITLE
Error at running at npm run command

### ISSUE THREAD

**Issue by Teja880** [Ihatetomatoes/react-image-slideshow#1]
After installing node modules...start the server
while i got error
>react-script start
Could not find a required file.
      Name: index.html
      Searched in:/<path of 01-start>/
this is command prompt error

**Comment by jrdevforlife** [comment]
You can just build the folder and file yourself. Create a file called index.html within a folder called public. Fill that index.html with it's standards and add a div with the id="root". Et voila there you go.
